### ISSUE TITLE
Dijkstra 3d path within a mask

### ISSUE THREAD

**Issue by RosieFerr** [seung-lab/dijkstra3d#38] opened 2023-05-11 13:01 UTC
I have a 3D numpy array of 0s and 1s, which represents a thresholded mask. I would like to find the shortest path of point A within the mask to point B within the mask. Does the dijkstra 3d algorithm calculate the shortest path within the mask of 1s? Or does use background points with value 0 as a part of the path?

**Comment by william-silversmith** [comment] 2023-05-11 14:42
Hi, thanks for writing in! The dijkstra algorithm here regards 0 as
background and uses the value of foreground as weights. So if you use all
ones, each move will be evenly weighted. However, the diagonals will not be
handled specially (e.g. sqrt(2), sqrt(3)) since it is just looking at the
field values.

Will

**Comment by RosieFerr** [comment] 2023-05-11 14:44
Dear Will, 

Thank you for the answer, but my question is still unclear to me:
Does the algorithm calculate paths that include the background voxels?

**Comment by william-silversmith** [comment] 2023-05-11 14:59
No, background voxels are excluded.

**Comment by RosieFerr** [comment] 2023-05-11 15:02
Thank you!

**Comment by RosieFerr** [comment] 2023-05-25 14:19
Hi William, I have tested your Dijkstra algorithm within my 3D numpy arrays of 0s and 1s however the algorithm still creates paths including the background voxels that have a value of 0. 
I have tried to increase the background voxel weights to for example 100 000 to avoid them as much as possible, but still if there is no other path possible the algorithm of course choses that voxel anyway.
I was wondering if there is a way to make the algorithm completely avoid the background voxels and simply return no path possible if there is no path between two voxels on the foreground, instead of including background voxels as it does now...

**Comment by william-silversmith** [comment] 2023-05-25 19:33
Hi Rosie,

My sincere apologies, it's been a while since I used it and forgot how I
was using it. There's no concept of a background color in this
implementation. However, if you use a floating point volume, you can
replace 0 with np.inf and that might do it.

I am considering providing a more simple to use function since this is such
a common request.

Will

**Comment by RosieFerr** [comment] 2023-05-25 19:46
Dear Will,

Thanks for the help!

Regards,
Rosaria

**Comment by william-silversmith** [comment] 2023-05-26 03:33
Hi Rosaria,

I've released a new version, 1.13.0, that has a (beta!) new function dijkstra.binary_dijkstra that will do what I think you are trying to accomplish. You can see how to use it on the front page.

Let me know if you have any questions.

Will

**Comment by RosieFerr** [comment] 2023-05-26 08:08
Thank you! I will try it out in the coming days!

**Comment by turtleizzy** [comment] 2023-06-11 02:38
We have discovered this issue when we try to calculate centerline using dijkstra3d, these two path are identical in the number of voxels (=length of path) but significantly different in euclidean arclen, the dark-blue line is generated by dijkstra3d.dijkstra.

![dingtalkgov_qt_clipbord_pic_3](https://github.com/seung-lab/dijkstra3d/assets/2318046/548d38bd-ed4a-452f-bf4e-7e018de5ecdf)

I am wondering is it possible to add an optional anisotropy parameter to dijkstra3d.dijkstra function. The expected behavior could be
1) if anisotropy = None, the behavior will be identical to current dijkstra3d.dijkstra
2) if anisotropy is provided, the edge weight will be multiplied with euclidean distance factor according to the anisotropy parameter.

**Comment by turtleizzy** [comment] 2023-06-11 04:07
I have added a [pull request](https://github.com/seung-lab/dijkstra3d/pull/41) for this feature.

>

**Comment by william-silversmith** [comment] 2023-12-19 04:49
I added a test and merged the PR. Thank you so much @turtleizzy !

**Closed by william-silversmith** 2023-12-19 04:49 UTC

**Comment by turtleizzy** [comment] 2023-12-19 08:39
Ahhh sooorryy I’ve been quite busy that days and I completely forgot this issue >_<

**Comment by william-silversmith** [comment] 2023-12-19 08:52
All good! Thank you for the contribution!
